SOURCES = [
    "Darth Vader",
    "Luke Skywalker",
    "Princess Leia",
    "Han Solo",
    "Obi-Wan Kenobi",
    "Yoda",
    "Palpatine",
    "Boba Fett",
    "Padmé Amidala",
    "Anakin Skywalker",

    "Death Star",
    "Lightsaber",
    "Millennium Falcon",
    "TIE fighter",
    "X-wing fighter",
    "The Force",
    "Jedi",
    "Sith",
    "Galactic Empire",
    "Rebel Alliance",
    "Clone trooper",
    "Stormtrooper (Star Wars)",
    "Star Wars: The Clone Wars",

    "Star Wars",
    "George Lucas",
    "Skywalker family",
    "Droids in Star Wars",
    "List of Star Wars planets and moons",
    "Star Wars species",
    "Star Wars vehicles",
    "Star Wars technology",
    "Star Wars in other media",
    "The Mandalorian"
]
